@startmindmap 工作

* 工作

** 2024工作内容
*** 区分业务需求、研发需求、自发需求(多做一些自动化研发,解放自己; 多做监控,保护自己; 多整理数据,证明自己).
*** 不要反感总结、分享, 把总结当成面试历练.
*** 每天抽出时间学习、复习专业内容.
*** 了解团队内、优酷整体的运营系统、技术链路.
*** 多看OKR目标, 日常工作和OKR对齐。
*** 跟业务同事多学习, 跳出程序员思维
*** 学习ATA同行业怎么做的
*** 用增行业学习



** 沟通能力
*** 描述问题五段论 1背景,2目标,3实现,4效果,5规划


** 35岁准备
*** 离职
**** 社保问题


*** 找工作


*** 副业




@endmindmap